export const REQUEST_PROJECT_LIST='REQUEST_PROJECT_LIST'
export const SUCCESS_PROJECT_LIST='SUCCESS_PROJECT_LIST'
export const FAILURE_PROJECT_LIST='FAILURE_PROJECT_LIST'


export const SUCCESS_LOGIN='SUCCESS_LOGIN'